import type { StudentNotification } from './notification.types';

export const notificationMockData: StudentNotification[] = [
  {
    id: 'attendance-opening',
    title: 'Attendance opens in 10 minutes',
    description: 'CS3203 · Architecture Review Lecture',
    timeLabel: '9:50',
    category: 'attendance',
    variant: 'info',
    icon: 'clock',
    isRead: false,
  },
  {
    id: 'qr-open',
    title: 'QR attendance is now open',
    description: 'MA3030 · Operational Research',
    timeLabel: '1:02 PM',
    category: 'attendance',
    variant: 'info',
    icon: 'qr-code',
    isRead: false,
  },
  {
    id: 'attendance-recorded',
    title: 'Attendance recorded successfully',
    description: 'CS3052 · Network Defence Lab',
    timeLabel: 'Yesterday',
    category: 'attendance',
    variant: 'success',
    icon: 'check-circle',
    isRead: true,
  },
  {
    id: 'attendance-missed',
    title: 'You missed the CS3052 attendance session',
    description: 'Computer Security · 14 Jul',
    timeLabel: 'Mon',
    category: 'attendance',
    variant: 'warning',
    icon: 'warning-triangle',
    isRead: true,
  },
  {
    id: 'attendance-low',
    title: 'Your attendance in MA3030 has fallen below 80%',
    description: 'Operational Research',
    timeLabel: '2 days ago',
    category: 'system',
    variant: 'error',
    icon: 'error-circle',
    isRead: true,
  },
  {
    id: 'location-changed',
    title: 'Attendance location changed to Lecture Hall 02',
    description: 'CS3203 · Software Eng. Project',
    timeLabel: '3 days ago',
    category: 'system',
    variant: 'info',
    icon: 'location',
    isRead: true,
  },
];
